version: 2
jobs:
  lint:
    docker:
      - image: hadolint/hadolint:v1.17.5-alpine
    steps:
      - checkout
      # - run: apk update
      # - run: apk add ca-certificates
      - run:
          name: Lint dockerfile
          command: |
            mkdir /tmp/linter
            ./scripts/lint.sh 2>&1 | tee outfile /tmp/linter/output
      - store_artifacts:
          path: /tmp/linter
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker image build --tag zenika/terraform-azure-cli:latest .
      - run:
          name: Save Docker image
          command: |
            mkdir workspace
            docker image save --output workspace/terraform-azure-cli-latest.tar zenika/terraform-azure-cli:latest
      - persist_to_workspace:
          root: workspace
          paths:
            - terraform-azure-cli-latest.tar
  build-tag:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker image build -t zenika/terraform-azure-cli:$CIRCLE_TAG .
      - run:
          name: Save Docker image
          command: |
            mkdir workspace
            docker image save --output workspace/terraform-azure-cli-${CIRCLE_TAG}.tar zenika/terraform-azure-cli:$CIRCLE_TAG
      - persist_to_workspace:
          root: workspace
          paths:
            - terraform-azure-cli-${CIRCLE_TAG}.tar
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Load Docker image
          command: |
            docker image load --input workspace/terraform-azure-cli-latest.tar
      - run:
          name: Publish latest Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
            docker push zenika/terraform-azure-cli:latest
  publish-tag:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Load Docker image
          command: |
            docker image load --input workspace/terraform-azure-cli-${CIRCLE_TAG}.tar
      - run:
          name: Publish tagged Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
            docker push zenika/terraform-azure-cli:$CIRCLE_TAG
workflows:
  version: 2
  test-and-build:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - build-tag:
          requires:
            - lint
          filters:
            tags:
              only: /[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - publish-latest:
          context: docker-hub
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-tag:
          context: docker-hub
          requires:
            - build
            - build-tag
          filters:
            tags:
              only: /[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
