name: lint-build-test

# trigger on any push
# but not on master, tags or redame modifications
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"
    paths-ignore:
      - "!README.md"
      - "!CODE_OF_CONDUCT.md.md"

env:
  # ORGANIZATION: "zenika"
  # IMAGE_NAME: "terraform-aws-cli"
  ORGANIZATION: "kstephens"
  IMAGE_NAME: "nonroot-user"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Save branch name as env var
        run: echo "::set-env name=BRANCH::${GITHUB_REF##*/}"

      - name: Build image
        run: docker image build . --file Dockerfile --tag $ORGANIZATION/$IMAGE_NAME:$BRANCH

      - name: Save image
        run: docker image save -o $IMAGE_NAME-$BRANCH.tar $ORGANIZATION/$IMAGE_NAME:$BRANCH

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.BRANCH }}
          path: ${{ env.IMAGE_NAME }}-${{ env.BRANCH }}.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Save branch name as env var
        run: echo "::set-env name=BRANCH::${GITHUB_REF##*/}"

      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.BRANCH }}

      - name: Load image
        run: docker image load --input $IMAGE_NAME-$BRANCH.tar

      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
          image: ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH }}
          config: tests/container-structure-tests.yml
