name: push-latest

# trigger on push to master
# only on image-related modifications
on:
  push:
    # branches:
    #   - "master"
    # paths:
    #   - "Dockerfile"
    #   - "supported_versions.json"
    #   - "hashicorp.asc"
    #   - "tests/**"
    #   - ".dockerignore"
    #   - ".github/workflows/push-latest.yml"

env:
  ORGANIZATION: "zenika"
  IMAGE_NAME: "terraform-aws-cli"
  IMAGE_TAG: "latest"

jobs:

  build_push_latest:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Retrieve latest suported versions
        run: |
          echo "AWS_VERSION=$(jq -r '.awscli_version | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV
          echo "TF_VERSION=$(jq -r '.tf_version | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV

      - name: Build image
        run: docker image build . --file Dockerfile --build-arg TERRAFORM_VERSION=${TF_VERSION} --build-arg AWS_CLI_VERSION=${AWS_VERSION} --tag $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: docker push $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Save image
        run: docker image save -o $IMAGE_NAME-$IMAGE_TAG.tar $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar
